### ISSUE TITLE
[BUG] Education landing page - Background Color Issue in "Practice what you learn" Section

### ISSUE THREAD

**Issue by marcoschamorro41** [aemsites/cmegroup#108]
The "Practice what you learn" section should have a white background, but in the current version, the background color does not match the expected design.

**Steps to Reproduce:**

1. Navigate to the Education page.
2. Scroll to the Practice what you learn section.
3. Compare the background color with the production version.

**Expected Result:**
The section background should be white, as seen in production.

<img width="845" alt="Image" src="https://github.com/user-attachments/assets/0ce0c654-94f5-450d-82cb-34b7013199ea" />

**Actual Result:**
The background color does not match production.
Needs alignment with the production design > https://www.cmegroup.com/education.html

![Image](https://github.com/user-attachments/assets/690a0c7f-fb9d-4606-b047-5bf5be8d3199)

**Comment by mlarco** [comment]
Nick mentioned this should be content configuration.
Is this a bug @kunwarsaluja or how can be configured?

**Comment by nkar-cme** [comment]
@kunwarsaluja @ndedios - I looked at the configuration and it doesn't look like this is able to be done in the current implementation. Is there a way we can match this?

**Comment by gustavoperti** [comment]
This issue was already solved.
As you can see in the image, when you configure a section-metadata between 2 section breaks, the styles you insert in it will be applied in that section of the page.

![Image](https://github.com/user-attachments/assets/8e3b183b-9d09-475f-b149-563d052af687)

**Comment by kunwarsaluja** [comment]
#108 is now marked closed. Please reopen incase anything specific to this issue is still missing or looks weird.

See updated doc : https://main--www--cmegroup.aem.live/education
